### ISSUE TITLE
TypeError: Cannot read property 'defineFunctionProperties' of undefined

### ISSUE THREAD

**Issue by francorobles** [serverless-heaven/serverless-webpack#1225]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
  Getting an error of TypeError: Cannot read property 'defineFunctionProperties' of undefined

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.9.0
* ***Webpack version you're using***: 4.43.0
* ***Serverless Framework Version you're using***: < 3
* ***Operating System***: Linux
* ***Stack Trace (if available)***:

```
TypeError: Cannot read property 'defineFunctionProperties' of undefined
--
  | at extendFunctionProperties (/app/node_modules/serverless-webpack/lib/extendServerless.js:4:51)
  | at new ServerlessWebpack (/app/node_modules/serverless-webpack/index.js:28:5)
  | at PluginManager.addPlugin (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:78:28)
  | at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:115:31
  | at Array.forEach (<anonymous>)
  | at PluginManager.loadAllPlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:115:8)
  | at /usr/lib/node_modules/serverless/lib/Serverless.js:96:35
  | at tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
  | at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
  | at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
  | at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
  | at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
  | at Promise._fulfill (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
  | at Promise._resolveCallback (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
  | at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
  | at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
  | at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
  | at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
  | at Promise._fulfill (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
  | at PromiseArray._resolve (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:127:19)
  | at PromiseArray._promiseFulfilled (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:145:14)
  | at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:609:26)
  | at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
  | at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
  | at Promise._fulfill (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
  | at Promise._resolveCallback (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
  | at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
  | at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
  | at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
  | at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
  | at Promise._fulfill (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
  | at PropertiesPromiseArray.PromiseArray._resolve (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:127:19)
  | at PropertiesPromiseArray._promiseFulfilled (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/props.js:78:14)
  | at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:609:26)
  | at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
  | at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
  | at Promise._fulfill (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
  | at Promise._resolveCallback (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
  | at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
  | at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
  | at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
  | at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
  | at _drainQueueStep (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
  | at _drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
  | at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
  | at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
  | at processImmediate (internal/timers.js:462:21)
```

**Comment by j0k3r** [comment]
Could you please tell us what command did you launch?
Maybe your `serverless.yml` file as well.

**Comment by crisecheverria** [comment]
Im having the exact same issue:

```
"serverless": "^1.77.1",
"serverless-webpack": "^5.2.0",
"webpack": "^4.29.0",
```

**Comment by vicary** [comment]
@crisecheverria You are using Serverless v1, #1126 should fix your issue. I want to make sure it works for @francorobles before releasing a patch.

Would you mind trying with serverless-webpack 5.8.0?

**Comment by crisecheverria** [comment]
@vicary tried with serverless-webpack 5.8.0 and the issue persists 

```
TypeError: Cannot read property 'defineFunctionProperties' of undefined
awsdeployment
      at extendFunctionProperties (/apollo/node_modules/serverless-webpack/lib/extendServerless.js:4:51)
```

**Comment by francorobles** [comment]
@crisecheverria @j0k3r @vicary this issue is now resolved. My bad, I double checked our private image and It was using  serverless < 2.x. I patched it to serverless 3.22.0 and serverless-webpack 5.9.0 and then the issue is gone.

**Comment by vicary** [comment]
@francorobles glad to hear that. We are trying our best to keep v1 backward compatible, so we'll release a patch shortly.

@crisecheverria Package managers tend to add a caret selector by default, i.e. `serverless-webpack@^5.8.0` you still get 5.9.0. You may also wait for 5.9.1 and try again.

**Comment by crisecheverria** [comment]
@vicary thanks for the reply, yes you’re right, after using "serverless-webpack": "5.8.0" the problem was solved for serverless v1 🎉
